export const DOG_API_CALL_REQUEST = "DOG_API_CALL_REQUEST";
export const DOG_API_CALL_SUCCESS = "DOG_API_CALL_SUCCESS";
export const DOG_API_CALL_FAILURE = "DOG_API_CALL_FAILURE";

export const CAT_API_CALL_REQUEST = "CAT_API_CALL_REQUEST";
export const CAT_API_CALL_SUCCESS = "CAT_API_CALL_SUCCESS";
export const CAT_API_CALL_FAILURE = "CAT_API_CALL_FAILURE";
